export default {
    username: 'Username',
    password: 'Mật khẩu',
    email: 'Email',
    login: 'Đăng nhập',
    welcome: 'Xin chào !',
    register: 'Đăng ký',
    forgotYourPassword: 'Quên mật khẩu ?',
    loginWithSocials: 'Hoặc đăng nhập bằng tài khoản mạng xã hội',
    registerWithSocials: 'Hoặc đăng ký bằng tài khoản mạng xã hội',
    invalidEmail: 'Email không hợp lệ',
    textRequired: '{{ text }} không được để trống',
    textCharacters: '{{ text }} phải có ít nhất {{ numbers }} kí tự',
    name: 'Tên',
    send: 'Gửi',
    forgotPassword: 'Quên mật khẩu',
    signUp: 'Đăng ký',
    categories: 'Danh mục sản phẩm',
    home: 'Trang chủ',
    check: 'Xem ngay',
    fashionSale: 'Fashion sale',
    new: 'Sản phẩm mới',
    homeSubTitle: "Sản phẩm giảm giá sốc !",
    viewAll: 'Xem ngay',
    shop: 'Shop',
    haveAnAccount: 'Đã có tài khoản ?',
    filters: 'Bộ lọc',
    priceRange: 'Khoảng giá',
    colors: 'Màu sắc',
    sizes: 'Kích cỡ',
    category: 'Danh mục',
    discard: 'Hủy bỏ',
    apply: 'Áp dụng',
    visualSearch: 'Visual Search',
    searchPhoto: 'Search by taking a photo',
    cropPhoto: 'Crop the item',
    findingResults: 'Finding similar results...',
    suggested: 'Gợi ý cho bạn',
    flashSale: 'Đang giảm giá',
};